apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quarkus-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.rewriteTarget }}
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: quarkus-api
            port:
              number: 8080
